version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build:
      context: ./app
    image: node-nginx-app
    container_name: app
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    command: sh buildAndRun.sh
    environment:
      - NODE_NGINX_APP_DB_HOST=mysql
      - NODE_NGINX_APP_PORT=${APP_PORT}
      - NODE_NGINX_APP_DB_NAME=${DB_NAME}
      - NODE_NGINX_APP_DB_USERNAME=${DB_USERNAME}
      - NODE_NGINX_APP_DB_PASSWORD=${DB_PASSWORD}
      - NODE_NGINX_APP_CONTAINER_TIMEOUT=${CONTAINER_TIMEOUT}
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    image: node-nginx-server
    container_name: nginx
    command: startNginx.sh
    environment:
      - NODE_NGINX_APP_PORT=${APP_PORT}
      - NODE_NGINX_APP_CONTAINER_TIMEOUT=${CONTAINER_TIMEOUT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
    - app